### ISSUE TITLE
Limit volume

### ISSUE THREAD

**Issue by daimaah** [Laberbear/node-discordbot#1]
Right now there are no checks for volume. I assume the intended range is from 0 to 1, or 1.5, but it's possible to set even higher for the bot's volume, making it VERY loud. A limit for the volume would be a nice thing to have.

**Comment by Laberbear** [comment]
Well there is a limit, but it is currently set to 5. Which is (undestandably) way too loud.
I'll lower the max volume to 1 in the next commit.

Thanks!
