### ISSUE TITLE
Probelm with setup/installing

### ISSUE THREAD

**Issue by IngveBoe** [Laberbear/node-discordbot#2]
im having some probelm. love the idea of a bot playing a spotify playlist. hopfully i can change the playlist and the bot will get the changes.

**Comment by Laberbear** [comment]
The bot (atleast the whole spotify streaming premise of it) doesn't work right anymore.
The module that is being used to get the Spotify streams and login is pretty much deprecated at this point.
Maybe this will change in the future.
